[toolchain]
anchor_version = "0.25.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_dapp = "PDmGe5v6jCkykenaS8gwMVNRMJ8rXA7Ag3c2ha3M9ZG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
