[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_dapp = "AKpH6fPQEV7cxF4mRtEsHwtdnYRcNiYwTu6BZYGqUz8u"

[programs.devnet]
lottery_dapp = "AKpH6fPQEV7cxF4mRtEsHwtdnYRcNiYwTu6BZYGqUz8u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
